# Generated by Django 3.1.4 on 2020-12-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfam_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafileentitycolumn',
            old_name='column_name',
            new_name='col_name',
        ),
        migrations.RenameField(
            model_name='datafilesubentitycolval',
            old_name='column_value',
            new_name='col_value',
        ),
        migrations.RenameField(
            model_name='remotesetentitycolval',
            old_name='column_value',
            new_name='col_value',
        ),
        migrations.AlterField(
            model_name='datafileentitycolumn',
            name='data_file_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='col', to='dfam_api_app.datafileentity'),
        ),
    ]
