# Generated by Django 3.1.4 on 2021-01-01 19:08

import dfam_api_app.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfam_api_app', '0004_auto_20201231_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilesub',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp'), upload_to=dfam_api_app.models.data_file_sub_upload_to),
        ),
        migrations.AlterField(
            model_name='userdatafiletype',
            name='data_file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_file_type_user', to='dfam_api_app.datafiletype'),
        ),
    ]
