# Generated by Django 3.1.4 on 2021-01-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dfam_api_app', '0005_auto_20210101_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilesub',
            name='data_file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_type_sub', to='dfam_api_app.datafiletype'),
            preserve_default=False,
        ),
    ]
